version: '3.6'

services:

  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: B012022
      POSTGRES_DB: inventory
      POSTGRES_PASSWORD: inventory.123
    ports:
      - 5432:5432